'use strict';

var coffeeCountries = ['Burundi', 
					  'Ethiopia', 
					  'Kenya', 
					  'Malawi', 
					  'Rwanda', 
					  'Tanzania', 
					  'Zambia', 
					  'Bolivia', 
					  'Brazil', 
					  'Colombia',
					  'Costa Rica',
					  'Cuba',
					  'Dominican Republic',
					  'Ecuador',
					  'El Salvador',
					  'Guatemala',
					  'Hawaii',
					  'Honduras',
					  'Jamaica',
					  'Mexico',
					  'Nicaragua',
					  'Panama',
					  'Peru',
					  'Venezuela',
					  'India',
					  'Indonesia',
					  'Papua New Guinea',
					  'Vietnam',
					  'Yemen'];
